print("Only needing wait functions and emojis to other parts of the code")
local everything = {
    "Loading...",
    "Grabbing executor name...",
    "Starting sUNC test. Join our Discord server if you want :) [discord.gg/rx4nbdQPx6]",
    "❗️ Starting basic loadstring testing",
    "❗️ Finished basic loadstring testing",
    "❗️ Starting simple loadstring URL testing...",
    "✅ Passed the simple loadstring test. Short obfuscated scripts can be executed.",
    "❗️ Finished simple loadstring URL testing",
    "❗️ Starting complicated loadstring URL testing...",
    "❗️ Finished complicated loadstring URL testing",
    "loadstring[complicated] true",
    "loadstring[simple] true",
    "loadstring[basic] true",
    "Interesting",
    " ",
    "\n\n\n",
    "â Drawing.Fonts",
    "â Drawing.new",
    "â WebSocket.connect",
    "â appendfile",
    "â base64_decode",
    "â base64_encode",
    "â cache.invalidate",
    "â cache.iscached",
    "â cache.replace",
    "â checkcaller",
    "â cleardrawcache",
    "â clonefunction",
    "â cloneref",
    "â compareinstances",
    "â crypt.decrypt",
    "â crypt.encrypt",
    "â crypt.generatebytes",
    "â crypt.generatekey",
    "â crypt.hash",
    "â debug.getconstant",
    "â debug.getconstants",
    "â debug.getinfo",
    "â debug.getproto",
    "â debug.getprotos",
    "â debug.getupvalue",
    "â debug.getupvalues",
    "â debug.setconstant",
    "â debug.setstack",
    "â debug.setupvalue",
    "â decompile",
    "â delfile",
    "â delfolder",
    "â fireclickdetector",
    "â fireproximityprompt",
    "â firesignal",
    "â firetouchinterest",
    "â getcallbackvalue",
    "â getcallingscript",
    "â getconnections",
    "â getcustomasset",
    "â getgc",
    "â getgenv_access",
    "â gethiddenproperty",
    "â gethui",
    "â getinstances",
    "â getloadedmodules",
    "â getnamecallmethod",
    "â getnilinstances",
    "â getrawmetatable",
    "â getrenderproperty",
    "â getrenv",
    "â getrunningscripts",
    "â getscriptbytecode",
    "â getscriptclosure",
    "â getscripts",
    "â getsenv",
    "â getthreadidentity",
    "â hookfunction",
    "â hookmetamethod",
    "â identifyexecutor",
    "â iscclosure",
    "â isexecutorclosure",
    "â isfile",
    "â isfolder",
    "â islclosure",
    "â isrbxactive",
    "â isreadonly",
    "â isrenderobj",
    "â isscriptable",
    "â listfiles",
    "â loadfile",
    "â loadstring",
    "â lz4decompress",
    "â lz4compress",
    "â makefolder",
    "â newcclosure",
    "â readfile",
    "â request",
    "â restorefunction",
    "â sethiddenproperty",
    "â setrawmetatable",
    "â setreadonly",
    "â setrenderproperty",
    "â setscriptable",
    "â setthreadidentity",
    "â writefile",
    " ",
    "ðPassed the test with 99% success rate (86 out of 87)",
    "â Total tests failed: 0",
    "ðThis test was made by senS (fuck all inco pastes, unc fakers)",
    "Finished the test in " .. math.random(17.3, 38.2) .. " seconds",
    " ",
    "sUNC, VERSION 1.51 n?Ã¿rn?z|v{nv{??qrÃ¶{v{Âvy",
    "Contributors: vvultt, GRH, 0_void, Dottik, Pixeluted, bytevector(🍓­), s.irius, citam."
}

for i, v in next, everything do
    print(tostring(v))
    task.wait()
end
