print("Loading...")
print("Grabbing executor name...")
print("STARTING sUNC test. Join our Discord server if you want :) [discord.gg/rx4nbdQPx6]")
wait(7)
print("     ")
print("❗ Starting basic loadstring testing")
wait(4)
print("❗ Finished basic loadstring testing")
print("❗ Starting simple loadstring URL testing...")
wait(4)
print("✅ Passed the simple loadstring test. Short obfuscated scripts can be executed.")
print("❗ Finished simple loadstring URL testing")
print("❗ Starting complicated loadstring URL testing...")
wait(4)
print("✅ Passed the complicated loadstring URL test.")
print("❗ Finished complicated loadstring URL testing")
wait(2)
print("loadstring[complicated] true")
print("loadstring[simple] true")
print("loadstring[basic] true")
print("      ")
print("      ")
print("      ")
print("      ")
wait(13)
print("Continuing test later since this is fake :D")
